name: rebase all

on:
  push:
 #   branches: [ "master" ]
  workflow_dispatch:
env:
    GH_TOKEN: ${{ github.token }}
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: rebase
      run: |
        gh search prs \
        --owner Tygozwolle \ 
        --state open \
        --label dependencies \
        --limit 200 \
        --json "url" --jq ".[] | .url" \
        | xargs -n 1 -I{} \
        sleep 10 \
        gh pr comment -b "@dependabot rebase" {}
