name: update registry

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Insecure Docker Repository
      run: |
        sudo truncate -s-2 /etc/docker/daemon.json
        echo ", \"insecure-registries\": [\"${{ vars.DOCKER_HOST }}\"]}" | sudo tee -a /etc/docker/daemon.json
        sudo systemctl restart docker
    - name: upload images
      run: |
        docker pull python:3.12.2-alpine3.19
        docker image tag python:3.12.2-alpine3.19 ${{ secrets.REGISTER_DOMAIN }}/python:3.12.2-alpine3.19
        docker push ${{ secrets.REGISTER_DOMAIN }}/python:3.12.2-alpine3.19 --insecure-registry ${{ secrets.REGISTER_DOMAIN }}
        
      
    
