name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: upload images
      run: |
        docker pull python:3.12.2-alpine3.19
        docker image tag python:3.12.2-alpine3.19 ${{ secrets.REGISTER_DOMAIN }}/python:3.12.2-alpine3.19
        docker push ${{ secrets.REGISTER_DOMAIN }}/python:3.12.2-alpine3.19
        
      
    
